"""removed deck_id from card

Revision ID: 5ee6e888019e
Revises: f4c1077d2e77
Create Date: 2018-08-20 16:26:26.694217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee6e888019e'
down_revision = 'f4c1077d2e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('deckname', sa.String(), nullable=False))
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.create_foreign_key(None, 'card', 'deck', ['deckname'], ['deckname'])
    op.drop_column('card', 'deck_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('deck_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.create_foreign_key(None, 'card', 'deck', ['deck_id'], ['id'])
    op.drop_column('card', 'deckname')
    # ### end Alembic commands ###
