"""added row deckname to Deck

Revision ID: f4c1077d2e77
Revises: 342419b20d61
Create Date: 2018-08-19 15:28:40.495207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c1077d2e77'
down_revision = '342419b20d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deck', sa.Column('deckname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deck', 'deckname')
    # ### end Alembic commands ###
